### ISSUE TITLE
/Library/Developer/CommandLineTools/usr/bin/make: unrecognized option `--output-sync=target'

### ISSUE THREAD

**Issue by marcocrio** [analogdevicesinc/VSCode-Maxim#20]
** Visual Studio Code version**
-1 .85.1 (Universal)

** C/C++ Extension version**
- v1.19.1

** Target microcontroller and evaluation platform**
- [e.g. MAX32666]

**Describe the bug**
- On MacOS with M1, M2 chips, make and gmake are both installed on the system it seems like. make only gets to version 3.81 currently and gmake goest to 4.4.1 and is designed for M1,M2 chips. 
- the '--output-sync=target' is only available after make version 4
- I solved it by installing gmake and replacing the command 'make' on the tasks.json file for 'gmake'

**To Reproduce**
1. Install the SDK on a M chip MacOS
2. Setup SDK path
3. tTy running any of the build tasks on VS Code's task.json file

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 14.2.1
 - Processor: Apple M2

**Comment by Jake-Carter** [comment]
Thanks @marcocrio 

I wrote some instructions for the MacOS setup at https://analog-devices-msdk.github.io/msdk/USERGUIDE/#completing-the-installation-on-macos

Can you confirm they work on your machine?  Brew should give you a symlink that you can pre-pend to your path to make gmake v4+ available as `make`

**Comment by Jake-Carter** [comment]
Should be fixed as of the [Feb 2024 release](https://github.com/analogdevicesinc/msdk/releases/tag/v2024_02).  We now distribute a Make v4.4.1 binary on MacOS as well, and prepend it to the PATH.  The setup instructions for MacOS now just involve running the brew command for installing OpenOCD dependencies.

**Comment by barmak** [comment]
> Thanks @marcocrio
> 
> I wrote some instructions for the MacOS setup at https://analog-devices-msdk.github.io/msdk/USERGUIDE/#completing-the-installation-on-macos
> 
> Can you confirm they work on your machine? Brew should give you a symlink that you can pre-pend to your path to make gmake v4+ available as `make`

Hello @Jake-Carter , it appear that the link you pointed out is dead. Can you confirm? Thanks.

**Comment by ttmut** [comment]
> > Thanks @marcocrio
> > I wrote some instructions for the MacOS setup at https://analog-devices-msdk.github.io/msdk/USERGUIDE/#completing-the-installation-on-macos
> > Can you confirm they work on your machine? Brew should give you a symlink that you can pre-pend to your path to make gmake v4+ available as `make`
> 
> Hello @Jake-Carter , it appears that the link you pointed out is dead. Can you confirm? Thanks.

Check this one https://analogdevicesinc.github.io/msdk//USERGUIDE/#completing-the-installation-on-macos

**Comment by barmak** [comment]
Thanks @ttmut , I struggle to find the instructios for the documentation note: "There are also some manual setup steps required to retrieve make version 4. The instructions in this section are critical."

My system `make` (`make -v`) gives me GNU Make 4.4.1.
But, when I run the same command on MS Code it returns GNU Make 3.81. Which is probably the source of the error in the title of this thread.

Any suggestion on how to update the `make` my VS code is using?
Thanks in advance.

**Comment by ttmut** [comment]
On system terminal, what is the output of `brew info make`?

**Comment by barmak** [comment]
> On system terminal, what is the output of `brew info make`?

```bash
❯ brew info make
==> make: stable 4.4.1 (bottled), HEAD
Utility for directing compilation
https://www.gnu.org/software/make/
Installed
/usr/local/Cellar/make/4.4.1 (17 files, 1.2MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-08-24 at 12:05:22
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/m/make.rb
License: GPL-3.0-only
==> Dependencies
Build: lzip ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
GNU "make" has been installed as "gmake".
If you need to use it as "make", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
==> Analytics
install: 11,006 (30 days), 33,209 (90 days), 133,402 (365 days)
install-on-request: 3,946 (30 days), 13,137 (90 days), 54,915 (365 days)
build-error: 11 (30 days)
```

But I think it is solved now. Probably by adding the system variables to my `.zshrc` (?)

Thanks a lot for the help!

**Comment by Jake-Carter** [comment]
@barmak we should be distributing make v4+ binaries now for MacOS.  The binary should be located at `$MAXIM_PATH/Tools/GNUTools/Make/make`, and this location gets pre-pended to VS Code's terminal PATH.

What does the command `$MAXIM_PATH/Tools/GNUTools/Make/make --version` return?

Also, are you running Intel or ARM silicon?  Maybe there is some mistake for the Intel silicon in our installer packaging.

**Comment by barmak** [comment]
@Jake-Carter , thanks for the update!

Here is what the command returns:
```bash
❯ $MAXIM_PATH/Tools/GNUTools/Make/make --version
GNU Make 4.4.1
Built for x86_64-apple-darwin19.6.0.  # <-- Intel silicon
...
``` 
Probably the changes on my `.zshrc` kicked in and now all my `makes` are v4.
Thanks again!
